
CREATE TABLE `AROrderItem` (
  
  `id` binary(18) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `docdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` binary(18) NOT NULL,
  `username` varchar(255) DEFAULT NULL,

  `ref` varchar(20) DEFAULT NULL,
  `reftype` varchar(20) DEFAULT NULL,
  `released` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(20) DEFAULT NULL,

  `business` binary(18) NOT NULL,
  `branch` binary(18) DEFAULT NULL,
  `branchno` varchar(100) DEFAULT NULL,
  `store` binary(18) DEFAULT NULL,
  `storeno` varchar(100) DEFAULT NULL,
  `storecell` binary(18) DEFAULT NULL,
  `storecellno` varchar(100) DEFAULT NULL,
  `warehouse` binary(18) DEFAULT NULL,
  `warehouseno` varchar(100) DEFAULT NULL,
  
  `ar_order` binary(18) NOT NULL,
  `ar_orderno` varchar(10) DEFAULT NULL,
  `ar_shipment` binary(18) DEFAULT NULL,
  `ar_shipmentno` varchar(10) DEFAULT NULL,
  `ar_shipmentitem` varchar(10) DEFAULT NULL,
  `ar_invoice` binary(18) DEFAULT NULL,
  `ar_invoiceno` varchar(10) DEFAULT NULL,
  `ar_invoiceitem` varchar(10) DEFAULT NULL,
  `ic_issue` binary(18) DEFAULT NULL,
  `ic_issueno` varchar(10) DEFAULT NULL,
  `ic_issueitem` varchar(10) DEFAULT NULL,
  `ap_purchase` binary(18) DEFAULT NULL,
  `ap_purchaseno` varchar(10) DEFAULT NULL,
  `ap_purchaseitem` varchar(10) DEFAULT NULL,
  
  `phonenum` varchar(20) DEFAULT NULL,
  `customer` binary(18) DEFAULT NULL,
  `customername` varchar(255) DEFAULT NULL,

  `item` binary(18) NOT NULL,
  `itemno` varchar(100) DEFAULT NULL,
  `itemdesc` varchar(10) DEFAULT NULL,
  `attr1` varchar(50) DEFAULT NULL,
  `attr2` varchar(50) DEFAULT NULL,
  `attr3` varchar(50) DEFAULT NULL,
  `attr4` varchar(50) DEFAULT NULL,
  `attr5` varchar(50) DEFAULT NULL,
  `lot` varchar(50) DEFAULT NULL,
  `UOM` varchar(8) NOT NULL DEFAULT 'BASE',
  `otherinfo` JSON DEFAULT NULL,
  `qty` decimal(15,8) NOT NULL,
  `unitprice` decimal(15,8) NOT NULL,
  `discpct`tinyint(4) DEFAULT NULL,
  `discamt` decimal(15,8) DEFAULT NULL,
  `VATpct`tinyint(4) DEFAULT NULL,
  `VATamt` decimal(15,8) DEFAULT NULL,
  `amount` decimal(15,8) NOT NULL,

  `shippable` tinyint(1) NOT NULL DEFAULT '1',
  `partialship` tinyint(1) NOT NULL DEFAULT '0',
  `shipinfo` JSON DEFAULT NULL,
  `shipping` decimal(15,8) DEFAULT NULL,
  `shipped` decimal(15,8) DEFAULT NULL,
  `shipremain` decimal(15,8) DEFAULT NULL,

  `invoiceinfo` JSON DEFAULT NULL,
  `invoicing` decimal(15,8) DEFAULT NULL,
  `invoicing_amt` decimal(15,8) DEFAULT NULL,
  `invoiced` decimal(15,8) DEFAULT NULL,
  `invoiced_amt` decimal(15,8) DEFAULT NULL,
  `invoice_remain` decimal(15,8) DEFAULT NULL,
  `invoice_remain_amt` decimal(15,8) DEFAULT NULL,
  
  `returned` decimal(15,8) DEFAULT NULL,
  `warrantied` decimal(15,8) DEFAULT NULL,

  `purchasable` tinyint(1) NOT NULL DEFAULT '0',
  `purchaseinfo` JSON DEFAULT NULL,
  `purchasing` decimal(15,8) DEFAULT NULL,
  `purchased` decimal(15,8) DEFAULT NULL,
  `purchase_remain` decimal(15,8) DEFAULT NULL,

  `checksum` bigint(20) NOT NULL,

  PRIMARY KEY (`id`),
  INDEX `SEARCH_INDEX_1`(`business` ASC,`created_at` ASC),
  INDEX `SEARCH_INDEX_2`(`user` ASC,`created_at` ASC) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;